version: '3.8'

services:
  # PostgreSQL Database for Development
  postgres:
    image: postgres:15
    container_name: django-oj-postgres-dev
    environment:
      POSTGRES_DB: django_oj
      POSTGRES_USER: oj_user
      POSTGRES_PASSWORD: oj_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Redis for Development
  redis:
    image: redis:7-alpine
    container_name: django-oj-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    restart: unless-stopped

volumes:
  postgres_dev_data:
  redis_dev_data:
