version: '3.8'

services:
  # Django Application
  web:
    build: .
    container_name: django-oj-web
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - ./sandbox_tmp:/app/sandbox_tmp
      - ./judge_temp:/app/judge_temp
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - db
      - redis
    restart: unless-stopped

  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: django-oj-db
    environment:
      POSTGRES_DB: django_oj
      POSTGRES_USER: oj_user
      POSTGRES_PASSWORD: oj_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: django-oj-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: django-oj-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
