# Generated by Django 4.2.24 on 2025-09-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgequeue',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='错误信息'),
        ),
    ]
