# Generated by Django 4.2.24 on 2025-09-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='solved_problems',
            field=models.ManyToManyField(blank=True, related_name='solvers', to='problems.problem', verbose_name='已解决题目'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
