# Generated by Django 4.2.24 on 2025-09-19 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python'), ('cpp', 'C++'), ('java', 'Java'), ('javascript', 'JavaScript')], max_length=20, verbose_name='编程语言')),
                ('code', models.TextField(verbose_name='代码')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('judging', '评测中'), ('accepted', '通过'), ('wrong_answer', '答案错误'), ('time_limit_exceeded', '超时'), ('memory_limit_exceeded', '内存超限'), ('runtime_error', '运行时错误'), ('compile_error', '编译错误'), ('system_error', '系统错误')], default='pending', max_length=25, verbose_name='状态')),
                ('time_used', models.PositiveIntegerField(blank=True, null=True, verbose_name='运行时间(ms)')),
                ('memory_used', models.PositiveIntegerField(blank=True, null=True, verbose_name='内存使用(KB)')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='得分')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('test_results', models.JSONField(blank=True, default=list, verbose_name='测试结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '提交记录',
                'verbose_name_plural': '提交记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
