# Generated by Django 4.2.24 on 2025-09-19 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='竞赛标题')),
                ('description', models.TextField(verbose_name='竞赛描述')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('duration', models.PositiveIntegerField(verbose_name='持续时间(分钟)')),
                ('status', models.CharField(choices=[('upcoming', '即将开始'), ('running', '进行中'), ('finished', '已结束')], default='upcoming', max_length=20, verbose_name='状态')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('password', models.CharField(blank=True, max_length=50, verbose_name='密码')),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True, verbose_name='最大参与人数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '竞赛',
                'verbose_name_plural': '竞赛',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='题目顺序')),
                ('points', models.PositiveIntegerField(default=100, verbose_name='分值')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contest', verbose_name='竞赛')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem', verbose_name='题目')),
            ],
            options={
                'verbose_name': '竞赛题目',
                'verbose_name_plural': '竞赛题目',
                'ordering': ['order'],
                'unique_together': {('contest', 'problem')},
            },
        ),
        migrations.CreateModel(
            name='ContestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_first_ac', models.BooleanField(default=False, verbose_name='是否首次通过')),
                ('penalty_time', models.PositiveIntegerField(default=0, verbose_name='罚时')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contest', verbose_name='竞赛')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contestproblem', verbose_name='竞赛题目')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='submissions.submission', verbose_name='提交记录')),
            ],
            options={
                'verbose_name': '竞赛提交',
                'verbose_name_plural': '竞赛提交',
            },
        ),
        migrations.AddField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(through='contests.ContestProblem', to='problems.problem', verbose_name='题目'),
        ),
        migrations.CreateModel(
            name='ContestParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='参与时间')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='总得分')),
                ('solved_count', models.PositiveIntegerField(default=0, verbose_name='解决题目数')),
                ('penalty', models.PositiveIntegerField(default=0, verbose_name='罚时(分钟)')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='contests.contest', verbose_name='竞赛')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '竞赛参与',
                'verbose_name_plural': '竞赛参与',
                'ordering': ['-score', 'penalty'],
                'unique_together': {('contest', 'user')},
            },
        ),
    ]
